In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat
import seaborn as sbn

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier



from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [2]:
data = pd.read_csv(r"D:\data\hr dataset\train.csv")
data.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [3]:
data.shape

(54808, 14)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             52399 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  KPIs_met >80%         54808 non-null  int64  
 11  awards_won?           54808 non-null  int64  
 12  avg_training_score    54808 non-null  int64  
 13  is_promoted           54808 non-null  int64  
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [5]:
data.describe()

employee_id  no_of_trainings           age  previous_year_rating  \
count  54808.000000     54808.000000  54808.000000          50684.000000   
mean   39195.830627         1.253011     34.803915              3.329256   
std    22586.581449         0.609264      7.660169              1.259993   
min        1.000000         1.000000     20.000000              1.000000   
25%    19669.750000         1.000000     29.000000              3.000000   
50%    39225.500000         1.000000     33.000000              3.000000   
75%    58730.500000         1.000000     39.000000              4.000000   
max    78298.000000        10.000000     60.000000              5.000000   

       length_of_service  KPIs_met >80%   awards_won?  avg_training_score  \
count       54808.000000   54808.000000  54808.000000        54808.000000   
mean            5.865512       0.351974      0.023172           63.386750   
std             4.265094       0.477590      0.150450           13.371559   
min             1.000000       0.000000      0.000000           39.000000   
25%             3.000000       0.000000      0.000000           51.000000   
50%             5.000000       0.000000      0.000000           60.000000   
75%             7.000000       1.000000      0.000000           76.000000   
max            37.000000       1.000000      1.000000           99.000000   

        is_promoted  
count  54808.000000  
mean       0.085170  
std        0.279137  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [6]:
data.describe(include="object")

department    region   education gender recruitment_channel
count               54808     54808       52399  54808               54808
unique                  9        34           3      2                   3
top     Sales & Marketing  region_2  Bachelor's      m               other
freq                16840     12343       36669  38496               30446

In [7]:
missing=data.isna().sum()
missing[missing>0]

education               2409
previous_year_rating    4124
dtype: int64

In [8]:
data.duplicated().sum()

0

In [9]:
data["education"].unique()

array(["Master's & above", "Bachelor's", nan, 'Below Secondary'],
      dtype=object)

# dealing with missing values

In [10]:
data["education"].fillna("Secondary",inplace=True)
data['previous_year_rating'].fillna(1,inplace=True)

In [11]:
# data=data[['department', 'region', 'education', 'gender',
#        'recruitment_channel', 'no_of_trainings', 'age',
#        'length_of_service', 'KPIs_met >80%', 'awards_won?',
#        'avg_training_score', 'is_promoted']]

# Data Pre-processing¶


In [12]:
label_encoder = LabelEncoder()
data["department"]=label_encoder.fit_transform(data["department"])
data["region"]=label_encoder.fit_transform(data["region"])
data["education"]=label_encoder.fit_transform(data["education"])
data["gender"]=label_encoder.fit_transform(data["gender"])
data["recruitment_channel"]=label_encoder.fit_transform(data["recruitment_channel"])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

In [13]:
inn=data[['department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age','previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score']]
         
out=data[['is_promoted']]

In [14]:
xtrain,xtest,ytrain,ytest=train_test_split(inn,out,test_size=0.2,random_state=0)

In [15]:
def score (pre):
    print(accuracy_score(pre,ytest)*100)
    print("----------------------------------")
    print(confusion_matrix(pre,ytest))
    print("----------------------------------")
    print(classification_report(pre,ytest))

# LogisticRegression

In [16]:
logistic_model=LogisticRegression()
logistic_model.fit(xtrain,ytrain)
#without&with standered scaler 91,5

C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
logistic_pre=logistic_model.predict(xtest)

In [18]:
score(logistic_pre)

91.59824849480022
----------------------------------
[[9957  837]
 [  84   84]]
----------------------------------
              precision    recall  f1-score   support

           0       0.99      0.92      0.96     10794
           1       0.09      0.50      0.15       168

    accuracy                           0.92     10962
   macro avg       0.54      0.71      0.56     10962
weighted avg       0.98      0.92      0.94     10962



# GaussianNB

In [19]:
naive_model=GaussianNB()
naive_model.fit(xtrain,ytrain)
#without&with standered scaler 91.3

C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [20]:
naive_pre=naive_model.predict(xtest)

In [21]:
score(naive_pre)

91.40667761357416
----------------------------------
[[9886  787]
 [ 155  134]]
----------------------------------
              precision    recall  f1-score   support

           0       0.98      0.93      0.95     10673
           1       0.15      0.46      0.22       289

    accuracy                           0.91     10962
   macro avg       0.57      0.69      0.59     10962
weighted avg       0.96      0.91      0.94     10962



# KNN

In [22]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(xtrain,ytrain)

C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [23]:
knn_pre=knn_model.predict(xtest)

In [24]:
score(knn_pre)

92.47400109469075
----------------------------------
[[9978  762]
 [  63  159]]
----------------------------------
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     10740
           1       0.17      0.72      0.28       222

    accuracy                           0.92     10962
   macro avg       0.58      0.82      0.62     10962
weighted avg       0.98      0.92      0.95     10962



# SVC

In [30]:
svc_model=SVC(kernel="linear",random_state=0)
svc_model.fit(xtrain,ytrain)

C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

In [33]:
svc_pre=svc_model.predict(xtest)

In [34]:
score(svc_pre)

91.59824849480022
----------------------------------
[[10041   921]
 [    0     0]]
----------------------------------
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     10962
           1       0.00      0.00      0.00         0

    accuracy                           0.92     10962
   macro avg       0.50      0.46      0.48     10962
weighted avg       1.00      0.92      0.96     10962



C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# DecisionTreeClassifier

In [41]:
dt=DecisionTreeClassifier(max_depth=5)
dt.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=5)

In [42]:
dt_pre=dt.predict(xtest)

In [43]:
score(dt_pre)

92.75679620507206
----------------------------------
[[10008   761]
 [   33   160]]
----------------------------------
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     10769
           1       0.17      0.83      0.29       193

    accuracy                           0.93     10962
   macro avg       0.59      0.88      0.62     10962
weighted avg       0.98      0.93      0.95     10962



# RandomForestClassifier

In [54]:
rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)

C:\Users\p&p\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [55]:
rf_pre=rf.predict(xtest)

In [56]:
score(rf_pre)

93.40448823207443
----------------------------------
[[9983  665]
 [  58  256]]
----------------------------------
              precision    recall  f1-score   support

           0       0.99      0.94      0.97     10648
           1       0.28      0.82      0.41       314

    accuracy                           0.93     10962
   macro avg       0.64      0.88      0.69     10962
weighted avg       0.97      0.93      0.95     10962

